# Generated by Django 3.2.7 on 2021-11-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_account_accountcurrency_accountstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcurrency',
            old_name='ammount',
            new_name='amount',
        ),
    ]
